before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  type: deploy
  environment:
    name: staging
    url: https://vostok.eginkaman.com
  script:
    - ssh www-root@80.82.222.33 "cd ./www/vostok.eginkaman.com && git checkout master && git pull origin master && /opt/php74/bin/php /var/www/www-root/data/bin/composer install && npm install && npm run prod && /opt/php74/bin/php artisan migrate --force && exit"
  only:
    - master
